window.GFCM_MEETINGS_DATA = [
  {
    "createdOn": "08/06/2026 10:42",
    "createdBy": "Christina Raftoudi",
    "createdByDelegate": "",
    "modifiedOn": "08/06/2026 10:42",
    "modifiedBy": "Christina Raftoudi",
    "modifiedByDelegate": "",
    "importSequenceNumber": "",
    "recordCreatedOn": "",
    "venue": "FAO HQ",
    "websiteSection": "",
    "websiteType": "",
    "websiteMeetings": "",
    "appearsInWebsite": "",
    "city": "Rome",
    "country": "",
    "expertGroup": "",
    "meetingCategory": "",
    "meetingCode": "",
    "meetingTitle": "",
    "meetingType": "",
    "session": "",
    "meetingStartDate": "",
    "meetingEndDate": "",
    "pkWebsiteMeetingEntry": "",
    "publicWebsiteUrl": "",
    "publicReportUrlEn": "",
    "publicReportUrlFr": "",
    "publicReportUrlAr": "",
    "publicReportUrlSp": "",
    "websiteLinkStayClickableUponExpiration": "",
    "status": "Active",
    "statusReason": "Active",
    "owner": "Christina Raftoudi",
    "owningBusinessUnit": "org02cf0e5c",
    "owningTeam": "",
    "owningUser": "",
    "timeZoneRuleVersionNumber": "0",
    "utcConversionTimeZoneCode": "",
    "versionNumber": "44132388"
  },
  {
    "createdOn": "08/06/2026 10:12",
    "createdBy": "Christina Raftoudi",
    "createdByDelegate": "",
    "modifiedOn": "08/06/2026 10:36",
    "modifiedBy": "Chiara Baffoni",
    "modifiedByDelegate": "Chiara Baffoni",
    "importSequenceNumber": "",
    "recordCreatedOn": "",
    "venue": "FAO HQ",
    "websiteSection": "",
    "websiteType": "",
    "websiteMeetings": "",
    "appearsInWebsite": "",
    "city": "Rome",
    "country": "",
    "expertGroup": "",
    "meetingCategory": "",
    "meetingCode": "",
    "meetingTitle": "",
    "meetingType": "",
    "session": "",
    "meetingStartDate": "",
    "meetingEndDate": "",
    "pkWebsiteMeetingEntry": "",
    "publicWebsiteUrl": "",
    "publicReportUrlEn": "",
    "publicReportUrlFr": "",
    "publicReportUrlAr": "",
    "publicReportUrlSp": "",
    "websiteLinkStayClickableUponExpiration": "",
    "status": "Active",
    "statusReason": "Active",
    "owner": "Christina Raftoudi",
    "owningBusinessUnit": "org02cf0e5c",
    "owningTeam": "",
    "owningUser": "",
    "timeZoneRuleVersionNumber": "0",
    "utcConversionTimeZoneCode": "",
    "versionNumber": "44132360"
  },
  {
    "createdOn": "08/06/2026 10:32",
    "createdBy": "Christina Raftoudi",
    "createdByDelegate": "",
    "modifiedOn": "08/06/2026 10:32",
    "modifiedBy": "Christina Raftoudi",
    "modifiedByDelegate": "",
    "importSequenceNumber": "",
    "recordCreatedOn": "",
    "venue": "NEA",
    "websiteSection": "",
    "websiteType": "",
    "websiteMeetings": "",
    "appearsInWebsite": "",
    "city": "Batumi",
    "country": "",
    "expertGroup": "",
    "meetingCategory": "",
    "meetingCode": "",
    "meetingTitle": "",
    "meetingType": "",
    "session": "",
    "meetingStartDate": "",
    "meetingEndDate": "",
    "pkWebsiteMeetingEntry": "",
    "publicWebsiteUrl": "",
    "publicReportUrlEn": "",
    "publicReportUrlFr": "",
    "publicReportUrlAr": "",
    "publicReportUrlSp": "",
    "websiteLinkStayClickableUponExpiration": "",
    "status": "Active",
    "statusReason": "Active",
    "owner": "Christina Raftoudi",
    "owningBusinessUnit": "org02cf0e5c",
    "owningTeam": "",
    "owningUser": "",
    "timeZoneRuleVersionNumber": "0",
    "utcConversionTimeZoneCode": "",
    "versionNumber": "44132327"
  },
  {
    "createdOn": "08/06/2026 10:29",
    "createdBy": "Christina Raftoudi",
    "createdByDelegate": "",
    "modifiedOn": "08/06/2026 10:29",
    "modifiedBy": "Christina Raftoudi",
    "modifiedByDelegate": "",
    "importSequenceNumber": "",
    "recordCreatedOn": "",
    "venue": "FAO HQ",
    "websiteSection": "",
    "websiteType": "",
    "websiteMeetings": "",
    "appearsInWebsite": "",
    "city": "Rome",
    "country": "",
    "expertGroup": "",
    "meetingCategory": "",
    "meetingCode": "",
    "meetingTitle": "",
    "meetingType": "",
    "session": "",
    "meetingStartDate": "",
    "meetingEndDate": "",
    "pkWebsiteMeetingEntry": "",
    "publicWebsiteUrl": "",
    "publicReportUrlEn": "",
    "publicReportUrlFr": "",
    "publicReportUrlAr": "",
    "publicReportUrlSp": "",
    "websiteLinkStayClickableUponExpiration": "",
    "status": "Active",
    "statusReason": "Active",
    "owner": "Christina Raftoudi",
    "owningBusinessUnit": "org02cf0e5c",
    "owningTeam": "",
    "owningUser": "",
    "timeZoneRuleVersionNumber": "0",
    "utcConversionTimeZoneCode": "",
    "versionNumber": "44132308"
  },
  {
    "createdOn": "08/06/2026 10:22",
    "createdBy": "Christina Raftoudi",
    "createdByDelegate": "",
    "modifiedOn": "08/06/2026 10:22",
    "modifiedBy": "Christina Raftoudi",
    "modifiedByDelegate": "",
    "importSequenceNumber": "",
    "recordCreatedOn": "",
    "venue": "FAO HQ",
    "websiteSection": "",
    "websiteType": "",
    "websiteMeetings": "",
    "appearsInWebsite": "",
    "city": "Rome",
    "country": "",
    "expertGroup": "",
    "meetingCategory": "",
    "meetingCode": "",
    "meetingTitle": "",
    "meetingType": "",
    "session": "",
    "meetingStartDate": "",
    "meetingEndDate": "",
    "pkWebsiteMeetingEntry": "",
    "publicWebsiteUrl": "",
    "publicReportUrlEn": "",
    "publicReportUrlFr": "",
    "publicReportUrlAr": "",
    "publicReportUrlSp": "",
    "websiteLinkStayClickableUponExpiration": "",
    "status": "Active",
    "statusReason": "Active",
    "owner": "Christina Raftoudi",
    "owningBusinessUnit": "org02cf0e5c",
    "owningTeam": "",
    "owningUser": "",
    "timeZoneRuleVersionNumber": "0",
    "utcConversionTimeZoneCode": "",
    "versionNumber": "44132227"
  },
  {
    "createdOn": "08/06/2026 10:19",
    "createdBy": "Christina Raftoudi",
    "createdByDelegate": "",
    "modifiedOn": "08/06/2026 10:19",
    "modifiedBy": "Christina Raftoudi",
    "modifiedByDelegate": "",
    "importSequenceNumber": "",
    "recordCreatedOn": "",
    "venue": "-",
    "websiteSection": "",
    "websiteType": "",
    "websiteMeetings": "",
    "appearsInWebsite": "",
    "city": "Rhodes",
    "country": "",
    "expertGroup": "",
    "meetingCategory": "",
    "meetingCode": "",
    "meetingTitle": "",
    "meetingType": "",
    "session": "",
    "meetingStartDate": "",
    "meetingEndDate": "",
    "pkWebsiteMeetingEntry": "",
    "publicWebsiteUrl": "",
    "publicReportUrlEn": "",
    "publicReportUrlFr": "",
    "publicReportUrlAr": "",
    "publicReportUrlSp": "",
    "websiteLinkStayClickableUponExpiration": "",
    "status": "Active",
    "statusReason": "Active",
    "owner": "Christina Raftoudi",
    "owningBusinessUnit": "org02cf0e5c",
    "owningTeam": "",
    "owningUser": "",
    "timeZoneRuleVersionNumber": "0",
    "utcConversionTimeZoneCode": "",
    "versionNumber": "44132212"
  },
  {
    "createdOn": "08/06/2026 10:15",
    "createdBy": "Christina Raftoudi",
    "createdByDelegate": "",
    "modifiedOn": "08/06/2026 10:15",
    "modifiedBy": "Christina Raftoudi",
    "modifiedByDelegate": "",
    "importSequenceNumber": "",
    "recordCreatedOn": "",
    "venue": "SUMAE - Central Fisheries Research Institute",
    "websiteSection": "",
    "websiteType": "",
    "websiteMeetings": "",
    "appearsInWebsite": "",
    "city": "Trabzon",
    "country": "",
    "expertGroup": "",
    "meetingCategory": "",
    "meetingCode": "",
    "meetingTitle": "",
    "meetingType": "",
    "session": "",
    "meetingStartDate": "",
    "meetingEndDate": "",
    "pkWebsiteMeetingEntry": "",
    "publicWebsiteUrl": "",
    "publicReportUrlEn": "",
    "publicReportUrlFr": "",
    "publicReportUrlAr": "",
    "publicReportUrlSp": "",
    "websiteLinkStayClickableUponExpiration": "",
    "status": "Active",
    "statusReason": "Active",
    "owner": "Christina Raftoudi",
    "owningBusinessUnit": "org02cf0e5c",
    "owningTeam": "",
    "owningUser": "",
    "timeZoneRuleVersionNumber": "0",
    "utcConversionTimeZoneCode": "",
    "versionNumber": "44131756"
  },
  {
    "createdOn": "04/06/2026 11:45",
    "createdBy": "Christina Raftoudi",
    "createdByDelegate": "",
    "modifiedOn": "08/06/2026 09:53",
    "modifiedBy": "Chiara Baffoni",
    "modifiedByDelegate": "Chiara Baffoni",
    "importSequenceNumber": "",
    "recordCreatedOn": "",
    "venue": "FAO HQ",
    "websiteSection": "",
    "websiteType": "",
    "websiteMeetings": "",
    "appearsInWebsite": "",
    "city": "Rome",
    "country": "",
    "expertGroup": "",
    "meetingCategory": "",
    "meetingCode": "",
    "meetingTitle": "",
    "meetingType": "",
    "session": "",
    "meetingStartDate": "",
    "meetingEndDate": "",
    "pkWebsiteMeetingEntry": "",
    "publicWebsiteUrl": "",
    "publicReportUrlEn": "",
    "publicReportUrlFr": "",
    "publicReportUrlAr": "",
    "publicReportUrlSp": "",
    "websiteLinkStayClickableUponExpiration": "",
    "status": "Active",
    "statusReason": "Active",
    "owner": "Christina Raftoudi",
    "owningBusinessUnit": "org02cf0e5c",
    "owningTeam": "",
    "owningUser": "",
    "timeZoneRuleVersionNumber": "0",
    "utcConversionTimeZoneCode": "",
    "versionNumber": "44131637"
  }
]
;
