// Auto-generated by Azure DevOps from Power Automate.
// Generated at: 2026-06-26T08:15:25Z
window.GFCM_MEETINGS_EXPORT = {
  "metadata": {
    "generatedAt": "2026-06-26T08:15:01.4998022Z",
    "source": "Dataverse",
    "environment": "GFCM Extranet Environment",
    "table": "new_website_meetingses",
    "tableDisplayName": "Website_Meetings",
    "tableId": "gfcm-website-meetings",
    "websitePageField": "_new_websitepage_value@OData.Community.Display.V1.FormattedValue"
  },
  "columns": [
    {
      "key": "new_appearsinwebsiteyn",
      "label": "Appears in Website Y/N",
      "type": "boolean"
    },
    {
      "key": "new_city",
      "label": "City",
      "type": "text"
    },
    {
      "key": "_new_country_value@OData.Community.Display.V1.FormattedValue",
      "label": "Country",
      "type": "lookup"
    },
    {
      "key": "_new_expertgroup_value@OData.Community.Display.V1.FormattedValue",
      "label": "Expert Group",
      "type": "lookup"
    },
    {
      "key": "_new_meetingcategory_value@OData.Community.Display.V1.FormattedValue",
      "label": "Meeting Category",
      "type": "lookup"
    },
    {
      "key": "_new_meetingcode_value@OData.Community.Display.V1.FormattedValue",
      "label": "Meeting Code",
      "type": "lookup"
    },
    {
      "key": "new_meetingenddate@OData.Community.Display.V1.FormattedValue",
      "label": "Meeting End Date",
      "type": "date"
    },
    {
      "key": "new_meetingstartdate@OData.Community.Display.V1.FormattedValue",
      "label": "Meeting Start Date",
      "type": "date"
    },
    {
      "key": "new_meetingtitle",
      "label": "Meeting Title",
      "type": "text"
    },
    {
      "key": "new_meetingtypes@OData.Community.Display.V1.FormattedValue",
      "label": "Meeting Type",
      "type": "choice"
    },
    {
      "key": "new_venue",
      "label": "Venue",
      "type": "text"
    },
    {
      "key": "new_publicreporturlar",
      "label": "Public Report URL (AR)",
      "type": "url"
    },
    {
      "key": "new_publicreporturlen",
      "label": "Public Report URL (EN)",
      "type": "url"
    },
    {
      "key": "new_publicreporturlfr",
      "label": "Public Report URL (FR)",
      "type": "url"
    },
    {
      "key": "new_publicreporturlsp",
      "label": "Public Report URL (SP)",
      "type": "url"
    },
    {
      "key": "new_publicwebsiteurl",
      "label": "Public website URL",
      "type": "url"
    },
    {
      "key": "_new_session_value@OData.Community.Display.V1.FormattedValue",
      "label": "Session",
      "type": "lookup"
    },
    {
      "key": "new_websitelinkstayclickableuponexpiration",
      "label": "Website link stay clickable upon expiration",
      "type": "boolean"
    },
    {
      "key": "_new_websitepage_value@OData.Community.Display.V1.FormattedValue",
      "label": "Website Page",
      "type": "lookup"
    },
    {
      "key": "_new_websitesection_value@OData.Community.Display.V1.FormattedValue",
      "label": "Website Section",
      "type": "lookup"
    },
    {
      "key": "_new_websitetype_value@OData.Community.Display.V1.FormattedValue",
      "label": "Website Type",
      "type": "lookup"
    },
    {
      "key": "new_websitemeetingid",
      "label": "Website_Meetings",
      "type": "text"
    }
  ],
  "rows": [
    {
      "@odata.etag": "W/\"44678463\"",
      "_owningbusinessunit_value@OData.Community.Display.V1.FormattedValue": "org02cf0e5c",
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "owningbusinessunit",
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname": "businessunit",
      "_owningbusinessunit_value": "5787272b-71ba-eb11-8235-000d3aad2dec",
      "modifiedon@OData.Community.Display.V1.FormattedValue": "6/26/2026 10:10 AM",
      "modifiedon": "2026-06-26T08:10:24Z",
      "versionnumber@OData.Community.Display.V1.FormattedValue": "44,678,463",
      "versionnumber": 44678463,
      "new_websitelinkstayclickableuponexpiration@OData.Community.Display.V1.FormattedValue": "No",
      "new_websitelinkstayclickableuponexpiration": false,
      "new_venue": "FAO HQ",
      "timezoneruleversionnumber@OData.Community.Display.V1.FormattedValue": "0",
      "timezoneruleversionnumber": 0,
      "new_appearsinwebsiteyn@OData.Community.Display.V1.FormattedValue": "No",
      "new_appearsinwebsiteyn": false,
      "_createdby_value@OData.Community.Display.V1.FormattedValue": "Christina Raftoudi",
      "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_createdby_value": "68c7c513-bf1d-ef11-840a-6045bd971244",
      "new_website_meetingsid": "ccb8b10b-d96e-f111-ab0d-6045bd87572e",
      "new_meetingtypes@OData.Community.Display.V1.FormattedValue": "GFCM Meetings",
      "new_meetingtypes": 100000000,
      "createdon@OData.Community.Display.V1.FormattedValue": "6/23/2026 9:56 AM",
      "createdon": "2026-06-23T07:56:36Z",
      "_new_country_value@OData.Community.Display.V1.FormattedValue": "Italy",
      "_new_country_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_Country",
      "_new_country_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_country",
      "_new_country_value": "c6e9b9f0-2616-f111-8341-6045bd87572e",
      "_new_expertgroup_value@OData.Community.Display.V1.FormattedValue": "SRC-CM",
      "_new_expertgroup_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_ExpertGroup",
      "_new_expertgroup_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_expertgroup",
      "_new_expertgroup_value": "6a0201a9-c015-f111-8341-6045bd87572e",
      "_new_meetingcategory_value@OData.Community.Display.V1.FormattedValue": "Fisheries (Mediterranean - SAC)",
      "_new_meetingcategory_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_MeetingCategory",
      "_new_meetingcategory_value@Microsoft.Dynamics.CRM.lookuplogicalname": "cr662_meeting_category",
      "_new_meetingcategory_value": "3b390f03-c015-f111-8341-6045bd8a5c65",
      "_modifiedonbehalfby_value@OData.Community.Display.V1.FormattedValue": "Chiara Baffoni",
      "_modifiedonbehalfby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_modifiedonbehalfby_value": "c9c26a1f-0acd-ef11-8ee9-6045bd958ea9",
      "statecode@OData.Community.Display.V1.FormattedValue": "Active",
      "statecode": 0,
      "_ownerid_value@OData.Community.Display.V1.FormattedValue": "Christina Raftoudi",
      "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "ownerid",
      "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_ownerid_value": "68c7c513-bf1d-ef11-840a-6045bd971244",
      "new_websitemeetingid": "WEB-1009",
      "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_owninguser_value": "68c7c513-bf1d-ef11-840a-6045bd971244",
      "new_city": "Rome",
      "statuscode@OData.Community.Display.V1.FormattedValue": "Active",
      "statuscode": 1,
      "new_meetingtitle": "Subregional Committee for the Eastern Mediterranean (SRC-EM)",
      "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "Chiara Baffoni",
      "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_modifiedby_value": "c9c26a1f-0acd-ef11-8ee9-6045bd958ea9",
      "new_meetingenddate@OData.Community.Display.V1.FormattedValue": "4/29/2026",
      "new_meetingenddate": "2026-04-29T00:00:00Z",
      "new_meetingstartdate@OData.Community.Display.V1.FormattedValue": "4/27/2026",
      "new_meetingstartdate": "2026-04-27T00:00:00Z",
      "websitePage": ""
    },
    {
      "@odata.etag": "W/\"44678459\"",
      "_new_websitetype_value@OData.Community.Display.V1.FormattedValue": "Technical meetings",
      "_new_websitetype_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_WebsiteType",
      "_new_websitetype_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_website_type",
      "_new_websitetype_value": "ce7c790b-ca5d-f111-a825-70a8a563f598",
      "_owningbusinessunit_value@OData.Community.Display.V1.FormattedValue": "org02cf0e5c",
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "owningbusinessunit",
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname": "businessunit",
      "_owningbusinessunit_value": "5787272b-71ba-eb11-8235-000d3aad2dec",
      "modifiedon@OData.Community.Display.V1.FormattedValue": "6/26/2026 10:10 AM",
      "modifiedon": "2026-06-26T08:10:22Z",
      "new_publicreporturlsp": "https://www.fao.org/gfcm/meetings/en/",
      "versionnumber@OData.Community.Display.V1.FormattedValue": "44,678,459",
      "versionnumber": 44678459,
      "new_websitelinkstayclickableuponexpiration@OData.Community.Display.V1.FormattedValue": "Yes",
      "new_websitelinkstayclickableuponexpiration": true,
      "new_venue": "NEA",
      "timezoneruleversionnumber@OData.Community.Display.V1.FormattedValue": "0",
      "timezoneruleversionnumber": 0,
      "new_publicwebsiteurl": "https://www.fao.org/gfcm/meetings/en/",
      "new_appearsinwebsiteyn@OData.Community.Display.V1.FormattedValue": "Yes",
      "new_appearsinwebsiteyn": true,
      "_createdby_value@OData.Community.Display.V1.FormattedValue": "Christina Raftoudi",
      "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_createdby_value": "68c7c513-bf1d-ef11-840a-6045bd971244",
      "new_website_meetingsid": "e663247c-ad6b-f111-a826-6045bd8a5c65",
      "_new_websitepage_value@OData.Community.Display.V1.FormattedValue": "Social acceptability",
      "_new_websitepage_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_WebsitePage",
      "_new_websitepage_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_website_pages",
      "_new_websitepage_value": "a904e2ff-865e-f111-a825-002248805fdc",
      "new_publicreporturlar": "https://www.fao.org/gfcm/meetings/en/",
      "new_meetingtypes@OData.Community.Display.V1.FormattedValue": "GFCM Meetings",
      "new_meetingtypes": 100000000,
      "createdon@OData.Community.Display.V1.FormattedValue": "6/19/2026 9:07 AM",
      "createdon": "2026-06-19T07:07:10Z",
      "_new_country_value@OData.Community.Display.V1.FormattedValue": "Georgia",
      "_new_country_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_Country",
      "_new_country_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_country",
      "_new_country_value": "de25a5f4-2616-f111-8341-6045bd879080",
      "_new_expertgroup_value@OData.Community.Display.V1.FormattedValue": "WKDATAPREP",
      "_new_expertgroup_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_ExpertGroup",
      "_new_expertgroup_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_expertgroup",
      "_new_expertgroup_value": "770201a9-c015-f111-8341-6045bd87572e",
      "_new_meetingcategory_value@OData.Community.Display.V1.FormattedValue": "Fisheries (Mediterranean - SAC)",
      "_new_meetingcategory_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_MeetingCategory",
      "_new_meetingcategory_value@Microsoft.Dynamics.CRM.lookuplogicalname": "cr662_meeting_category",
      "_new_meetingcategory_value": "3b390f03-c015-f111-8341-6045bd8a5c65",
      "_new_websitesection_value@OData.Community.Display.V1.FormattedValue": "Main page",
      "_new_websitesection_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_WebsiteSection",
      "_new_websitesection_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_website_sections",
      "_new_websitesection_value": "ffe9f425-ca5d-f111-a825-70a8a563f598",
      "_modifiedonbehalfby_value@OData.Community.Display.V1.FormattedValue": "Chiara Baffoni",
      "_modifiedonbehalfby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_modifiedonbehalfby_value": "c9c26a1f-0acd-ef11-8ee9-6045bd958ea9",
      "statecode@OData.Community.Display.V1.FormattedValue": "Active",
      "statecode": 0,
      "new_publicreporturlfr": "https://www.fao.org/gfcm/meetings/en/",
      "_ownerid_value@OData.Community.Display.V1.FormattedValue": "Christina Raftoudi",
      "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "ownerid",
      "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_ownerid_value": "68c7c513-bf1d-ef11-840a-6045bd971244",
      "new_websitemeetingid": "WEB-1008",
      "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_owninguser_value": "68c7c513-bf1d-ef11-840a-6045bd971244",
      "new_city": "Batumi",
      "new_publicreporturlen": "https://www.fao.org/gfcm/meetings/en/",
      "statuscode@OData.Community.Display.V1.FormattedValue": "Active",
      "statuscode": 1,
      "new_meetingtitle": "Data Preparation Meeting on Stock Assessment for the Black Sea (GSA 29)\t(SGSABS)",
      "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "Chiara Baffoni",
      "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_modifiedby_value": "c9c26a1f-0acd-ef11-8ee9-6045bd958ea9",
      "new_meetingenddate@OData.Community.Display.V1.FormattedValue": "6/12/2026",
      "new_meetingenddate": "2026-06-12T00:00:00Z",
      "_new_session_value@OData.Community.Display.V1.FormattedValue": "Session BS",
      "_new_session_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_Session",
      "_new_session_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_session",
      "_new_session_value": "a305dbf6-2616-f111-8341-6045bd87572e",
      "new_meetingstartdate@OData.Community.Display.V1.FormattedValue": "6/8/2026",
      "new_meetingstartdate": "2026-06-08T00:00:00Z",
      "websitePage": "Social acceptability"
    }
  ]
}
;

window.GFCM_MEETINGS_METADATA = window.GFCM_MEETINGS_EXPORT.metadata;
window.GFCM_MEETINGS_COLUMNS = window.GFCM_MEETINGS_EXPORT.columns;
window.GFCM_MEETINGS_DATA = window.GFCM_MEETINGS_EXPORT.rows;
