// Auto-generated by Azure DevOps from Power Automate.
// Generated at: 2026-06-28T01:00:20Z
window.GFCM_MEETINGS_EXPORT = {
  "metadata": {
    "generatedAt": "2026-06-28T01:00:02.6264724Z",
    "source": "Dataverse",
    "environment": "GFCM Extranet Environment",
    "table": "new_website_meetingses",
    "tableDisplayName": "Website_Meetings",
    "tableId": "gfcm-website-meetings",
    "websitePageField": "_new_websitepage_value@OData.Community.Display.V1.FormattedValue"
  },
  "columns": [
    {
      "key": "new_appearsinwebsiteyn",
      "label": "Appears in Website Y/N",
      "type": "boolean"
    },
    {
      "key": "new_city",
      "label": "City",
      "type": "text"
    },
    {
      "key": "_new_country_value@OData.Community.Display.V1.FormattedValue",
      "label": "Country",
      "type": "lookup"
    },
    {
      "key": "_new_expertgroup_value@OData.Community.Display.V1.FormattedValue",
      "label": "Expert Group",
      "type": "lookup"
    },
    {
      "key": "_new_meetingcategory_value@OData.Community.Display.V1.FormattedValue",
      "label": "Meeting Category",
      "type": "lookup"
    },
    {
      "key": "_new_meetingcode_value@OData.Community.Display.V1.FormattedValue",
      "label": "Meeting Code",
      "type": "lookup"
    },
    {
      "key": "new_meetingenddate@OData.Community.Display.V1.FormattedValue",
      "label": "Meeting End Date",
      "type": "date"
    },
    {
      "key": "new_meetingstartdate@OData.Community.Display.V1.FormattedValue",
      "label": "Meeting Start Date",
      "type": "date"
    },
    {
      "key": "new_meetingtitle",
      "label": "Meeting Title",
      "type": "text"
    },
    {
      "key": "new_meetingtypes@OData.Community.Display.V1.FormattedValue",
      "label": "Meeting Type",
      "type": "choice"
    },
    {
      "key": "new_venue",
      "label": "Venue",
      "type": "text"
    },
    {
      "key": "new_publicreporturlar",
      "label": "Public Report URL (AR)",
      "type": "url"
    },
    {
      "key": "new_publicreporturlen",
      "label": "Public Report URL (EN)",
      "type": "url"
    },
    {
      "key": "new_publicreporturlfr",
      "label": "Public Report URL (FR)",
      "type": "url"
    },
    {
      "key": "new_publicreporturlsp",
      "label": "Public Report URL (SP)",
      "type": "url"
    },
    {
      "key": "new_publicwebsiteurl",
      "label": "Public website URL",
      "type": "url"
    },
    {
      "key": "_new_session_value@OData.Community.Display.V1.FormattedValue",
      "label": "Session",
      "type": "lookup"
    },
    {
      "key": "new_websitelinkstayclickableuponexpiration",
      "label": "Website link stay clickable upon expiration",
      "type": "boolean"
    },
    {
      "key": "_new_websitepage_value@OData.Community.Display.V1.FormattedValue",
      "label": "Website Page",
      "type": "lookup"
    },
    {
      "key": "_new_websitesection_value@OData.Community.Display.V1.FormattedValue",
      "label": "Website Section",
      "type": "lookup"
    },
    {
      "key": "_new_websitetype_value@OData.Community.Display.V1.FormattedValue",
      "label": "Website Type",
      "type": "lookup"
    },
    {
      "key": "new_websitemeetingid",
      "label": "Website_Meetings",
      "type": "text"
    }
  ],
  "rows": [
    {
      "@odata.etag": "W/\"44678721\"",
      "_new_websitetype_value@OData.Community.Display.V1.FormattedValue": "Technical meetings",
      "_new_websitetype_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_WebsiteType",
      "_new_websitetype_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_website_type",
      "_new_websitetype_value": "ce7c790b-ca5d-f111-a825-70a8a563f598",
      "_owningbusinessunit_value@OData.Community.Display.V1.FormattedValue": "org02cf0e5c",
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "owningbusinessunit",
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname": "businessunit",
      "_owningbusinessunit_value": "5787272b-71ba-eb11-8235-000d3aad2dec",
      "modifiedon@OData.Community.Display.V1.FormattedValue": "6/26/2026 11:22 AM",
      "modifiedon": "2026-06-26T09:22:45Z",
      "new_publicreporturlsp": "https://openknowledge.fao.org/handle/20.500.14283/ce0156en",
      "versionnumber@OData.Community.Display.V1.FormattedValue": "44,678,721",
      "versionnumber": 44678721,
      "new_websitelinkstayclickableuponexpiration@OData.Community.Display.V1.FormattedValue": "Yes",
      "new_websitelinkstayclickableuponexpiration": true,
      "new_venue": "-",
      "timezoneruleversionnumber@OData.Community.Display.V1.FormattedValue": "0",
      "timezoneruleversionnumber": 0,
      "new_appearsinwebsiteyn@OData.Community.Display.V1.FormattedValue": "Yes",
      "new_appearsinwebsiteyn": true,
      "_createdby_value@OData.Community.Display.V1.FormattedValue": "Christina Raftoudi",
      "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_createdby_value": "68c7c513-bf1d-ef11-840a-6045bd971244",
      "new_website_meetingsid": "0ac030ab-3b71-f111-ab0d-6045bd8a5c65",
      "_new_websitepage_value@OData.Community.Display.V1.FormattedValue": "Allocated zones for aquaculture",
      "_new_websitepage_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_WebsitePage",
      "_new_websitepage_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_website_pages",
      "_new_websitepage_value": "1d4289bf-885e-f111-a825-002248805fdc",
      "new_publicreporturlar": "https://openknowledge.fao.org/handle/20.500.14283/ce0156en",
      "new_meetingtypes@OData.Community.Display.V1.FormattedValue": "GFCM Meetings",
      "new_meetingtypes": 100000000,
      "createdon@OData.Community.Display.V1.FormattedValue": "6/26/2026 10:47 AM",
      "createdon": "2026-06-26T08:47:36Z",
      "_new_country_value@OData.Community.Display.V1.FormattedValue": "Bulgaria",
      "_new_country_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_Country",
      "_new_country_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_country",
      "_new_country_value": "dc25a5f4-2616-f111-8341-6045bd879080",
      "_new_expertgroup_value@OData.Community.Display.V1.FormattedValue": "WKDATAPREP",
      "_new_expertgroup_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_ExpertGroup",
      "_new_expertgroup_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_expertgroup",
      "_new_expertgroup_value": "770201a9-c015-f111-8341-6045bd87572e",
      "_new_meetingcategory_value@OData.Community.Display.V1.FormattedValue": "Fisheries (Black Sea - ACBS)",
      "_new_meetingcategory_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_MeetingCategory",
      "_new_meetingcategory_value@Microsoft.Dynamics.CRM.lookuplogicalname": "cr662_meeting_category",
      "_new_meetingcategory_value": "e019e726-a423-f111-8341-6045bd87572e",
      "_new_websitesection_value@OData.Community.Display.V1.FormattedValue": "Main page",
      "_new_websitesection_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_WebsiteSection",
      "_new_websitesection_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_website_sections",
      "_new_websitesection_value": "ffe9f425-ca5d-f111-a825-70a8a563f598",
      "statecode@OData.Community.Display.V1.FormattedValue": "Active",
      "statecode": 0,
      "new_publicreporturlfr": "https://openknowledge.fao.org/handle/20.500.14283/ce0156en",
      "_new_meetingcode_value@OData.Community.Display.V1.FormattedValue": "MTG-1037",
      "_new_meetingcode_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_MeetingCode",
      "_new_meetingcode_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_meeting_transactional_data",
      "_new_meetingcode_value": "3ca187c3-3771-f111-ab0d-6045bd8a5c65",
      "_ownerid_value@OData.Community.Display.V1.FormattedValue": "Christina Raftoudi",
      "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "ownerid",
      "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_ownerid_value": "68c7c513-bf1d-ef11-840a-6045bd971244",
      "new_websitemeetingid": "WEB-1010",
      "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_owninguser_value": "68c7c513-bf1d-ef11-840a-6045bd971244",
      "new_city": "Burgas",
      "new_publicreporturlen": "https://openknowledge.fao.org/handle/20.500.14283/ce0156en",
      "statuscode@OData.Community.Display.V1.FormattedValue": "Active",
      "statuscode": 1,
      "new_meetingtitle": "Subregional Group on stock assessment for the Black Sea (SGSABS), including a session of the Working Group on Fisheries and Climate Change",
      "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "Chiara Baffoni",
      "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_modifiedby_value": "c9c26a1f-0acd-ef11-8ee9-6045bd958ea9",
      "new_meetingenddate@OData.Community.Display.V1.FormattedValue": "7/10/2026",
      "new_meetingenddate": "2026-07-10T00:00:00Z",
      "new_meetingstartdate@OData.Community.Display.V1.FormattedValue": "7/6/2026",
      "new_meetingstartdate": "2026-07-06T00:00:00Z",
      "websitePage": "Allocated zones for aquaculture"
    },
    {
      "@odata.etag": "W/\"44678716\"",
      "_new_websitetype_value@OData.Community.Display.V1.FormattedValue": "Technical meetings",
      "_new_websitetype_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_WebsiteType",
      "_new_websitetype_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_website_type",
      "_new_websitetype_value": "ce7c790b-ca5d-f111-a825-70a8a563f598",
      "_owningbusinessunit_value@OData.Community.Display.V1.FormattedValue": "org02cf0e5c",
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "owningbusinessunit",
      "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname": "businessunit",
      "_owningbusinessunit_value": "5787272b-71ba-eb11-8235-000d3aad2dec",
      "modifiedon@OData.Community.Display.V1.FormattedValue": "6/26/2026 11:22 AM",
      "modifiedon": "2026-06-26T09:22:40Z",
      "versionnumber@OData.Community.Display.V1.FormattedValue": "44,678,716",
      "versionnumber": 44678716,
      "new_websitelinkstayclickableuponexpiration@OData.Community.Display.V1.FormattedValue": "Yes",
      "new_websitelinkstayclickableuponexpiration": true,
      "new_venue": "FAO HQ",
      "timezoneruleversionnumber@OData.Community.Display.V1.FormattedValue": "0",
      "timezoneruleversionnumber": 0,
      "new_appearsinwebsiteyn@OData.Community.Display.V1.FormattedValue": "Yes",
      "new_appearsinwebsiteyn": true,
      "_createdby_value@OData.Community.Display.V1.FormattedValue": "Christina Raftoudi",
      "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_createdby_value": "68c7c513-bf1d-ef11-840a-6045bd971244",
      "new_website_meetingsid": "e6ea19b2-3b71-f111-ab0c-000d3a4745d5",
      "_new_websitepage_value@OData.Community.Display.V1.FormattedValue": "Animal health and welfare",
      "_new_websitepage_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_WebsitePage",
      "_new_websitepage_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_website_pages",
      "_new_websitepage_value": "86b0e9f0-865e-f111-a825-002248805fdc",
      "new_publicreporturlar": "https://openknowledge.fao.org/handle/20.500.14283/cd9950en",
      "new_meetingtypes@OData.Community.Display.V1.FormattedValue": "GFCM Meetings",
      "new_meetingtypes": 100000000,
      "createdon@OData.Community.Display.V1.FormattedValue": "6/26/2026 10:47 AM",
      "createdon": "2026-06-26T08:47:46Z",
      "_new_country_value@OData.Community.Display.V1.FormattedValue": "Italy",
      "_new_country_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_Country",
      "_new_country_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_country",
      "_new_country_value": "c6e9b9f0-2616-f111-8341-6045bd87572e",
      "_new_expertgroup_value@OData.Community.Display.V1.FormattedValue": "SRC-AS",
      "_new_expertgroup_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_ExpertGroup",
      "_new_expertgroup_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_expertgroup",
      "_new_expertgroup_value": "482f3eaa-c015-f111-8341-00224882a531",
      "_new_meetingcategory_value@OData.Community.Display.V1.FormattedValue": "Fisheries (Mediterranean - SAC)",
      "_new_meetingcategory_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_MeetingCategory",
      "_new_meetingcategory_value@Microsoft.Dynamics.CRM.lookuplogicalname": "cr662_meeting_category",
      "_new_meetingcategory_value": "3b390f03-c015-f111-8341-6045bd8a5c65",
      "_new_websitesection_value@OData.Community.Display.V1.FormattedValue": "Main page",
      "_new_websitesection_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_WebsiteSection",
      "_new_websitesection_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_website_sections",
      "_new_websitesection_value": "ffe9f425-ca5d-f111-a825-70a8a563f598",
      "statecode@OData.Community.Display.V1.FormattedValue": "Active",
      "statecode": 0,
      "new_publicreporturlfr": "https://openknowledge.fao.org/handle/20.500.14283/cd9950en",
      "_new_meetingcode_value@OData.Community.Display.V1.FormattedValue": "MTG-1038",
      "_new_meetingcode_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "new_MeetingCode",
      "_new_meetingcode_value@Microsoft.Dynamics.CRM.lookuplogicalname": "new_meeting_transactional_data",
      "_new_meetingcode_value": "d9321852-3b71-f111-ab0d-6045bd8a5c65",
      "_ownerid_value@OData.Community.Display.V1.FormattedValue": "Christina Raftoudi",
      "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "ownerid",
      "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_ownerid_value": "68c7c513-bf1d-ef11-840a-6045bd971244",
      "new_websitemeetingid": "WEB-1011",
      "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_owninguser_value": "68c7c513-bf1d-ef11-840a-6045bd971244",
      "new_city": "Rome",
      "new_publicreporturlen": "https://openknowledge.fao.org/handle/20.500.14283/cd9950en",
      "statuscode@OData.Community.Display.V1.FormattedValue": "Active",
      "statuscode": 1,
      "new_meetingtitle": "Subregional Committee for the Adriatic Sea (SRC-AS)",
      "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "Chiara Baffoni",
      "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
      "_modifiedby_value": "c9c26a1f-0acd-ef11-8ee9-6045bd958ea9",
      "new_meetingenddate@OData.Community.Display.V1.FormattedValue": "5/28/2026",
      "new_meetingenddate": "2026-05-28T00:00:00Z",
      "new_meetingstartdate@OData.Community.Display.V1.FormattedValue": "5/26/2026",
      "new_meetingstartdate": "2026-05-26T00:00:00Z",
      "websitePage": "Animal health and welfare"
    }
  ]
}
;

window.GFCM_MEETINGS_METADATA = window.GFCM_MEETINGS_EXPORT.metadata;
window.GFCM_MEETINGS_COLUMNS = window.GFCM_MEETINGS_EXPORT.columns;
window.GFCM_MEETINGS_DATA = window.GFCM_MEETINGS_EXPORT.rows;
