// Auto-generated by Azure DevOps from Power Automate.
// Generated at: 2026-06-27T22:14:10Z
window.myTableData = [
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "OTH-GFCM/30/2006/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":44,\"Value\":\"1976\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC-CM-GFCM/13/1976/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":23,\"Value\":\"1997\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/22/1997/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":18,\"Value\":\"2002\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/27/2002/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":15,\"Value\":\"2005\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/29/2005/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/30/2006/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/30/2006/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/30/2006/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":13,\"Value\":\"2007\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/31/2007/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/33/2009/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/33/2009/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/35/2011/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/35/2011/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/35/2011/4",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/35/2011/5",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.DIR-GFCM/33/2009/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.DIR-GFCM/33/2009/4",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.DIR-GFCM/33/2009/5",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.DIR-GFCM/35/2011/6",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":19,\"Value\":\"2001\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/26/2001/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":15,\"Value\":\"2005\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/29/2005/3(A)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":15,\"Value\":\"2005\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/29/2005/3(B)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":15,\"Value\":\"2005\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/29/2005/3(C)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":15,\"Value\":\"2005\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/29/2005/3(D)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":15,\"Value\":\"2005\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/29/2005/3(E)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":15,\"Value\":\"2005\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/29/2005/3(F)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":13,\"Value\":\"2007\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/31/2007/3(A)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":13,\"Value\":\"2007\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/31/2007/3(B)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":13,\"Value\":\"2007\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/31/2007/3(C)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":12,\"Value\":\"2008\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/32/2008/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/33/2009/9(A)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/33/2009/9(B)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/33/2009/9(C)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":10,\"Value\":\"2010\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/34/2010/4(A)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":10,\"Value\":\"2010\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/34/2010/4(B)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":10,\"Value\":\"2010\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/34/2010/4(C)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/35/2011/7(A)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/35/2011/7(B)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/35/2011/7(C)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/35/2011/7(D)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/35/2011/7(E)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/30/2006/5",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":12,\"Value\":\"2008\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/32/2008/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/33/2009/6",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/33/2009/7",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/33/2009/8",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":10,\"Value\":\"2010\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/34/2010/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":10,\"Value\":\"2010\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/34/2010/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":10,\"Value\":\"2010\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/34/2010/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/35/2011/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":40,\"Value\":\"1980\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/15/1980/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":40,\"Value\":\"1980\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/15/1980/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":40,\"Value\":\"1980\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/15/1980/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":25,\"Value\":\"1995\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/21/1995/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":15,\"Value\":\"2005\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/29/2005/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/30/2006/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":13,\"Value\":\"2007\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/31/2007/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":13,\"Value\":\"2007\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/31/2007/4",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":12,\"Value\":\"2008\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/32/2008/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/33/2009/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/33/2009/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/35/2011/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/35/2011/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":9,\"Value\":\"2011\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/35/2011/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":8,\"Value\":\"2012\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/36/2012/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":8,\"Value\":\"2012\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/36/2012/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":8,\"Value\":\"2012\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/36/2012/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":6,\"Value\":\"2014\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/38/2014/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":6,\"Value\":\"2014\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/38/2014/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":6,\"Value\":\"2014\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/38/2014/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":7,\"Value\":\"2013\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/37/2013/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":7,\"Value\":\"2013\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/37/2013/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":7,\"Value\":\"2013\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/37/2013/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":15,\"Value\":\"2005\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/29/2005/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS.-GFCM/30/2006/4",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC-GFCM/30/2006/7",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.ICCAT-GFCM/2006/8(B)",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":7,\"Value\":\"2013\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/37/2013/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":8,\"Value\":\"2012\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/36/2012/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":7,\"Value\":\"2013\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "OTH-GFCM/37/2013/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":7,\"Value\":\"2013\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "OTH-GFCM/37/2013/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":6,\"Value\":\"2014\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "OTH-GFCM/38/2014/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":8,\"Value\":\"2012\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "OTH-GFCM/36/2012/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":5,\"Value\":\"2015\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/39/2015/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":5,\"Value\":\"2015\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/39/2015/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":5,\"Value\":\"2015\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/39/2015/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":5,\"Value\":\"2015\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/39/2015/4",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":4,\"Value\":\"2016\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/40/2016/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":4,\"Value\":\"2016\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.DIR-GFCM/40/2016/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":4,\"Value\":\"2016\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/40/2016/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":4,\"Value\":\"2016\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/40/2016/4",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":4,\"Value\":\"2016\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/40/2016/5",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":4,\"Value\":\"2016\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/40/2016/6",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":4,\"Value\":\"2016\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/40/2016/7",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":4,\"Value\":\"2016\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/40/2016/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":4,\"Value\":\"2016\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/40/2016/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":4,\"Value\":\"2016\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "RES-GFCM/40/2016/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":3,\"Value\":\"2017\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.DIR-GFCM/41/2017/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":3,\"Value\":\"2017\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/41/2017/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":3,\"Value\":\"2017\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/41/2017/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  }
]
;
