// Auto-generated by Azure DevOps from Power Automate.
// Generated at: 2026-06-24T13:51:22Z
window.myTableData = [
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "OTH-GFCM/30/2006/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":44,\"Value\":\"1976\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC-CM-GFCM/13/1976/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":23,\"Value\":\"1997\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/22/1997/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":18,\"Value\":\"2002\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/27/2002/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":15,\"Value\":\"2005\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/29/2005/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/30/2006/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/30/2006/2",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":14,\"Value\":\"2006\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/30/2006/3",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":13,\"Value\":\"2007\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/31/2007/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  },
  {
    "year": "{\"@odata.type\":\"#Microsoft.Azure.Connectors.SharePoint.SPListExpandedReference\",\"Id\":11,\"Value\":\"2009\"}",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/33/2009/1",
    "files": [
      {
        "label": "EN",
        "url": "<English file URL>"
      },
      {
        "label": "FR",
        "url": "<French file URL>"
      }
    ]
  }
]
;
