// Auto-generated by Azure DevOps from Power Automate.
// Generated at: 2026-07-09T07:31:03Z
window.myTableData = [
  {
    "year": "",
    "type": "",
    "category": "",
    "number": "",
    "title": "OTH-GFCM/30/2006/1",
    "files": []
  },
  {
    "year": "",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC-CM-GFCM/13/1976/3",
    "files": []
  },
  {
    "year": "",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.MCS-GFCM/22/1997/1",
    "files": []
  },
  {
    "year": "",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/27/2002/1",
    "files": []
  },
  {
    "year": "",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/29/2005/1",
    "files": []
  },
  {
    "year": "",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/30/2006/1",
    "files": []
  },
  {
    "year": "",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/30/2006/2",
    "files": []
  },
  {
    "year": "",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/30/2006/3",
    "files": []
  },
  {
    "year": "",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/31/2007/1",
    "files": []
  },
  {
    "year": "",
    "type": "",
    "category": "",
    "number": "",
    "title": "REC.CM-GFCM/33/2009/1",
    "files": []
  }
]
;
