window.myTableData = [
  {
    "decisionStatus": "",
    "year": "",
    "type": "Null",
    "category": "",
    "number": "1",
    "title": "OTH-GFCM/30/2006/1",
    "decision": "OTH-GFCM/30/2006/1",
    "decisionType": "",
    "description": "",
    "summaryScope": "",
    "relatedDecisions": "",
    "gsas": "",
    "requiresYearlyClarification": "",
    "decisionTopics": "",
    "amendedBy": "",
    "repealedBy": "",
    "validityStarted": "",
    "validityEnded": "",
    "modified": "",
    "files": []
  },
  {
    "decisionStatus": "",
    "year": "",
    "type": "Null",
    "category": "",
    "number": "3",
    "title": "REC-CM-GFCM/13/1976/3",
    "decision": "REC-CM-GFCM/13/1976/3",
    "decisionType": "",
    "description": "",
    "summaryScope": "",
    "relatedDecisions": "",
    "gsas": "",
    "requiresYearlyClarification": "",
    "decisionTopics": "",
    "amendedBy": "",
    "repealedBy": "",
    "validityStarted": "",
    "validityEnded": "",
    "modified": "",
    "files": []
  },
  {
    "decisionStatus": "",
    "year": "",
    "type": "Null",
    "category": "",
    "number": "1",
    "title": "REC.MCS-GFCM/22/1997/1",
    "decision": "REC.MCS-GFCM/22/1997/1",
    "decisionType": "",
    "description": "",
    "summaryScope": "",
    "relatedDecisions": "",
    "gsas": "",
    "requiresYearlyClarification": "",
    "decisionTopics": "",
    "amendedBy": "",
    "repealedBy": "",
    "validityStarted": "",
    "validityEnded": "",
    "modified": "",
    "files": []
  },
  {
    "decisionStatus": "",
    "year": "",
    "type": "Null",
    "category": "",
    "number": "1",
    "title": "REC.CM-GFCM/27/2002/1",
    "decision": "REC.CM-GFCM/27/2002/1",
    "decisionType": "",
    "description": "",
    "summaryScope": "",
    "relatedDecisions": "",
    "gsas": "",
    "requiresYearlyClarification": "",
    "decisionTopics": "",
    "amendedBy": "",
    "repealedBy": "",
    "validityStarted": "",
    "validityEnded": "",
    "modified": "",
    "files": []
  },
  {
    "decisionStatus": "",
    "year": "",
    "type": "Null",
    "category": "",
    "number": "1",
    "title": "REC.CM-GFCM/29/2005/1",
    "decision": "REC.CM-GFCM/29/2005/1",
    "decisionType": "",
    "description": "",
    "summaryScope": "",
    "relatedDecisions": "",
    "gsas": "",
    "requiresYearlyClarification": "",
    "decisionTopics": "",
    "amendedBy": "",
    "repealedBy": "",
    "validityStarted": "",
    "validityEnded": "",
    "modified": "",
    "files": []
  },
  {
    "decisionStatus": "",
    "year": "",
    "type": "Null",
    "category": "",
    "number": "1",
    "title": "REC.CM-GFCM/30/2006/1",
    "decision": "REC.CM-GFCM/30/2006/1",
    "decisionType": "",
    "description": "",
    "summaryScope": "",
    "relatedDecisions": "",
    "gsas": "",
    "requiresYearlyClarification": "",
    "decisionTopics": "",
    "amendedBy": "",
    "repealedBy": "",
    "validityStarted": "",
    "validityEnded": "",
    "modified": "",
    "files": []
  },
  {
    "decisionStatus": "",
    "year": "",
    "type": "Null",
    "category": "",
    "number": "2",
    "title": "REC.CM-GFCM/30/2006/2",
    "decision": "REC.CM-GFCM/30/2006/2",
    "decisionType": "",
    "description": "",
    "summaryScope": "",
    "relatedDecisions": "",
    "gsas": "",
    "requiresYearlyClarification": "",
    "decisionTopics": "",
    "amendedBy": "",
    "repealedBy": "",
    "validityStarted": "",
    "validityEnded": "",
    "modified": "",
    "files": []
  },
  {
    "decisionStatus": "",
    "year": "",
    "type": "Null",
    "category": "",
    "number": "3",
    "title": "REC.CM-GFCM/30/2006/3",
    "decision": "REC.CM-GFCM/30/2006/3",
    "decisionType": "",
    "description": "",
    "summaryScope": "",
    "relatedDecisions": "",
    "gsas": "",
    "requiresYearlyClarification": "",
    "decisionTopics": "",
    "amendedBy": "",
    "repealedBy": "",
    "validityStarted": "",
    "validityEnded": "",
    "modified": "",
    "files": []
  },
  {
    "decisionStatus": "",
    "year": "",
    "type": "Null",
    "category": "",
    "number": "1",
    "title": "REC.CM-GFCM/31/2007/1",
    "decision": "REC.CM-GFCM/31/2007/1",
    "decisionType": "",
    "description": "",
    "summaryScope": "",
    "relatedDecisions": "",
    "gsas": "",
    "requiresYearlyClarification": "",
    "decisionTopics": "",
    "amendedBy": "",
    "repealedBy": "",
    "validityStarted": "",
    "validityEnded": "",
    "modified": "",
    "files": []
  },
  {
    "decisionStatus": "",
    "year": "",
    "type": "Null",
    "category": "",
    "number": "1",
    "title": "REC.CM-GFCM/33/2009/1",
    "decision": "REC.CM-GFCM/33/2009/1",
    "decisionType": "",
    "description": "",
    "summaryScope": "",
    "relatedDecisions": "",
    "gsas": "",
    "requiresYearlyClarification": "",
    "decisionTopics": "",
    "amendedBy": "",
    "repealedBy": "",
    "validityStarted": "",
    "validityEnded": "",
    "modified": "",
    "files": []
  }
]
;
